### ISSUE TITLE
[feature request]: --jb-select-width & --jb-select-scale (css variables)

### ISSUE THREAD

**Issue by Sinakhx** [javadbat/jb-select#3]
in our project we need to be able to set the width & scale of the jb-select component to be well fitted into every desired form of any scale. by now, scaling is possible by using a wrapper component but there is no way to set the width (or max-width) of the jb-select component itself.

thanks in advance for considering issues & maintaining this great library.

**Comment by javadbat** [comment]
thank you sina
by default jb-select will be fit to its container width and you can change its width by changing the parent DOM width. anyway if you currently need a different width for your select component you can set `--jb-select-width` CSS variable base on your need
