### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by mahsahmd** [javadbat/jb-select#8]
hi,
I need to be able to add an icon to select input before or after the placeholder, like the picture below
![Capture](https://user-images.githubusercontent.com/55913696/174723793-1d65531e-37e3-41ca-af00-6f06a8e822fd.JPG)
thanks in advance

**Comment by javadbat** [comment]
# Add an Icon or Any Element into the box
sometimes you want to add an icon into the select box before the value box.
you can customize this entire section by adding a div or any other Tag with the `slot="start-section"`

like the example below:

```html
<jb-select>
    <div slot="start-section">
        <img class="your-custom-icon" src="./path/to/file.svg">
    </div>
</jb-select>
```
